name: "Build/test"

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '.github/dependabot.yml'
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.github/dependabot.yml'
  workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - quarkus3-todo
          - quarkus3-reactive-todo
          - springboot3-todo
          - springboot3-reactive-todo
    name: build-test-${{ matrix.project }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Run build
        working-directory: ${{ matrix.project }}
        run: ./mvnw -B clean verify